version: "3.8"

services:
  # ── Observability Stack ──
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logi_net

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - logi_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - logi_net
    depends_on:
      - loki

  # ── Message Queue ──
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - logi_net

  # ── Python ML Service ──
  ml-service:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"
    networks:
      - logi_net

  # ── Node.js API Server ──
  api-server:
    build:
      context: ./server
    expose:
      - "5000"
    environment:
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - ML_SERVICE_URL=http://ml-service:8000
      - LOKI_URL=http://loki:3100
      - JWT_SECRET=super_secret_hackathon_key_freight_mind
      - PII_ENCRYPTION_KEY=0123456789abcdef0123456789abcdef
    networks:
      - logi_net
    depends_on:
      - redis
      - loki
      - ml-service

  # ── Node.js Background Worker ──
  worker:
    build:
      context: ./server
    command: node workers/worker.js
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - ML_SERVICE_URL=http://ml-service:8000
      - LOKI_URL=http://loki:3100
      - PII_ENCRYPTION_KEY=0123456789abcdef0123456789abcdef
    networks:
      - logi_net
    depends_on:
      - redis

  # ── Node.js Background Worker 2 (Parallelisation) ──
  worker-2:
    build:
      context: ./server
    command: node workers/worker.js
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - ML_SERVICE_URL=http://ml-service:8000
      - LOKI_URL=http://loki:3100
      - PII_ENCRYPTION_KEY=0123456789abcdef0123456789abcdef
    networks:
      - logi_net
    depends_on:
      - redis

  # ── React Vite Frontend ──
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_DOCKERIZED=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - logi_net
    depends_on:
      - api-server

networks:
  logi_net:
    driver: bridge
